name: Lint and Check Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'

      - name: Install dependencies
        run: npm install

      - name: Check lint and formatting
        run: npm run check
