name: Run tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'

      - name: Run tests
        id: test
        run: 
          npm installs
          npm run test

      - name: Check test results
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const checkRunId = ${{ steps.test.outputs.check_run_id }}
            const checkRunResult = ${{ github.event.pull_request.status }}
            const checkRunOutput = ${{ steps.test.outputs.check_output }}

            console.log('checkRunId:', checkRunId)
            console.log('checkRunResult:', checkRunResult)
            console.log('checkRunOutput:', checkRunOutput)

            const octokit = github.getOctokit();
            const checkRunData = {
              name: 'Tests',
              output: {
                summary: checkRunOutput,
                text: checkRunOutput,
              },
              status: checkRunResult,
            };

            await octokit.checks.update({
              check_run_id: checkRunId,
              owner: context.repo.owner,
              repo: context.repo.repo,
              input: checkRunData,
            });
